[versions]
#major = "0"
#minor = "xx"
#patch = "0"
minSdk = "31"
compileSdk = "34"
targetSdk = "34"

# dependencies
aboutlibrariesVersion = "11.1.1"
acraVersion = "5.11.3"
appcompatVersion = "1.7.0"
cardviewVersion = "1.0.0"
cyclonedxVersion = "1.8.2"
daggerVersion = "2.51"
dependencyCheckVersion = "9.0.10"
designVersion = "28.0.0"
errorproneVersion = "3.1.0"
errorpronecoreVersion = "2.4.0"
#espressoVersion = "3.3.0"
exifinterfaceVersion = "1.3.7"
fragmentKtxVersion = "1.8.3"
gsonVersion = "2.10.1"
kotlinxCoroutinesCore = "1.8.0"
materialVersion = "1.12.0"
okhttpVersion = "5.0.0-alpha.10"
picassoVersion = "2.8"
preferenceKtxVersion = "1.2.1"
recyclerviewVersion = "1.3.2"
securityCryptoVersion = "1.1.0-alpha06"
tesseract4androidOpenmpVersion = "4.2.0"

# plugins
gradlePluginVersion = "8.5.2"
kotlinGradlePluginVersion = "1.9.21"
scabbardPluginVersion = "0.5.0"

[libraries]
aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutlibrariesVersion" }
aboutlibraries-plugin = { group = "com.mikepenz.aboutlibraries.plugin", name = "aboutlibraries-plugin", version.ref = "aboutlibrariesVersion" }
acra-mail = { group = "ch.acra", name = "acra-mail", version.ref = "acraVersion" }
acra-toast = { group = "ch.acra", name = "acra-toast", version.ref = "acraVersion" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardviewVersion" }
cyclonedx-gradle-plugin = { group = "org.cyclonedx", name = "cyclonedx-gradle-plugin", version.ref = "cyclonedxVersion" }
dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "daggerVersion" }
dependency-check-plugin = { group = "org.owasp", name = "dependency-check-gradle", version.ref = "dependencyCheckVersion" }
design = { group = "com.android.support", name = "design", version.ref = "designVersion" }
error-prone-core = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorpronecoreVersion" }
exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterfaceVersion" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtxVersion" }
androidGradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePluginVersion" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGradlePluginVersion" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttpVersion" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picassoVersion" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtxVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewVersion" }
scabbard-gradle-plugin = { group = "gradle.plugin.dev.arunkumar", name = "scabbard-gradle-plugin", version.ref = "scabbardPluginVersion" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCryptoVersion" }
tesseract4android-openmp = { group = "cz.adaptech.tesseract4android", name = "tesseract4android-openmp", version.ref = "tesseract4androidOpenmpVersion" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibrariesVersion" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedxVersion" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencyCheckVersion" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorproneVersion" }
scabbard = { id = "scabbard.gradle", version.ref = "scabbardPluginVersion" }
